version: '3.8'
services:
  pg_db:
    container_name: db_container
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= postgres
      - POSTGRES_DB= bookmarks
    restart: always
    volumes:
      - pg_db:/data/db
    networks:
      - wolo

  api:
    container_name: back_container
    build: ./
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@pg_db:5432/bookmarks?schema=public
      - JWT_SECRET=bookmarks-management-jwt-secret-key
      - JWT_EXPIRY=8600s
      - PORT=3000
    depends_on:
      - pg_db
    volumes:
      - bookmark_back:/app

  front:
    container_name: front_container
    build: ./bookmark-management-frontend/
    ports:
      - "80:8001"
    depends_on:
      - api
    volumes:
      - bookmark_front:/app

networks:
  wolo:
volumes:
  pg_db:
  bookmark_back:
  bookmark_front:
