version: '3.8'
services:
  dev-db:
    container_name: db_container
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= postgres
      - POSTGRES_DB= bookmarks
    volumes:
      - dev_db:/data/db
    networks:
      - wolo
networks:
  wolo:
volumes:
  dev_db:
